import type { PortalProperty } from "./types";

/** A complete, publishable property; override fields per test. Not exported publicly. */
export function makePortalProperty(overrides: Partial<PortalProperty> = {}): PortalProperty {
  const base: PortalProperty = {
    reference: "H88-000001",
    slug: "kallithea-apartment-h88-000001",
    listingType: "SALE",
    propertyType: "APARTMENT",
    status: "ACTIVE",
    condition: "GOOD",
    titleEl: "Διαμέρισμα στην Καλλιθέα",
    titleEn: "Apartment in Kallithea",
    descriptionEl: "Φωτεινό διαμέρισμα 3ου ορόφου.",
    descriptionEn: "Bright third-floor apartment.",
    price: 250000,
    priceOnRequest: false,
    monthlyRent: null,
    area: 120,
    plotArea: null,
    builtArea: 118,
    bedrooms: 3,
    bathrooms: 2,
    wc: 1,
    floor: 3,
    totalFloors: 5,
    yearBuilt: 2005,
    yearRenovated: 2020,
    heating: "CENTRAL",
    energyClass: "B",
    hasSolar: true,
    parking: true,
    parkingSpaces: 1,
    storage: true,
    balcony: true,
    balconyArea: 20,
    garden: false,
    pool: false,
    furnished: false,
    petsAllowed: true,
    seaView: false,
    newConstruction: false,
    region: "Αττική",
    city: "Καλλιθέα",
    areaName: "Κέντρο",
    neighborhood: null,
    address: "Λεωφόρος Θησέως 100",
    postalCode: "17676",
    latitude: 37.9583,
    longitude: 23.7175,
    videoUrl: null,
    virtualTourUrl: null,
    media: [
      { kind: "PHOTO", url: "https://cdn.home88.gr/h88-000001/1.jpg", alt: "Σαλόνι", sortOrder: 0, isPrimary: false },
      { kind: "PHOTO", url: "https://cdn.home88.gr/h88-000001/2.jpg", alt: "Κουζίνα", sortOrder: 1, isPrimary: true },
      { kind: "FLOOR_PLAN", url: "https://cdn.home88.gr/h88-000001/plan.pdf", alt: null, sortOrder: 0, isPrimary: false },
    ],
    updatedAt: "2026-10-01T09:00:00.000Z",
  };

  return { ...base, ...overrides };
}
